package auth.model;

import base.model.BaseModel;

public class Module extends BaseModel {

	/**
	 * Database Column Remarks: 主键 This field was generated by MyBatis Generator. This field corresponds to the database column user_auth_module.id
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 * Database Column Remarks: 模块名称 This field was generated by MyBatis Generator. This field corresponds to the database column user_auth_module.name
	 * @mbg.generated
	 */
	private String name;
	/**
	 * Database Column Remarks: 是否可用 This field was generated by MyBatis Generator. This field corresponds to the database column user_auth_module.enabled
	 * @mbg.generated
	 */
	private String enabled;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_auth_module.id
	 * @return  the value of user_auth_module.id
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_auth_module.id
	 * @param id  the value for user_auth_module.id
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_auth_module.name
	 * @return  the value of user_auth_module.name
	 * @mbg.generated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_auth_module.name
	 * @param name  the value for user_auth_module.name
	 * @mbg.generated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user_auth_module.enabled
	 * @return  the value of user_auth_module.enabled
	 * @mbg.generated
	 */
	public String getEnabled() {
		return enabled;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user_auth_module.enabled
	 * @param enabled  the value for user_auth_module.enabled
	 * @mbg.generated
	 */
	public void setEnabled(String enabled) {
		this.enabled = enabled == null ? null : enabled.trim();
	}

	@Override
	public String toString() {
		return "Module [id=" + id + ", name=" + name + ", enabled=" + enabled + "]";
	}

}