package base.model;

import java.util.Date;

public class BaseModel {
	
	/**
	 * Database Column Remarks: 乐观锁 This field was generated by MyBatis Generator. This field corresponds to the database column user_auth_menu.REVISION
	 * @mbg.generated
	 */
	private Integer revision;
	/**
	 * Database Column Remarks: 创建人 This field was generated by MyBatis Generator. This field corresponds to the database column user_auth_menu.CREATED_BY
	 * @mbg.generated
	 */
	private String createdBy;
	/**
	 * Database Column Remarks: 创建时间 This field was generated by MyBatis Generator. This field corresponds to the database column user_auth_menu.CREATED_TIME
	 * @mbg.generated
	 */
	private Date createdTime;
	/**
	 * Database Column Remarks: 更新人 This field was generated by MyBatis Generator. This field corresponds to the database column user_auth_menu.UPDATED_BY
	 * @mbg.generated
	 */
	private String updatedBy;
	/**
	 * Database Column Remarks: 更新时间 This field was generated by MyBatis Generator. This field corresponds to the database column user_auth_menu.UPDATED_TIME
	 * @mbg.generated
	 */
	private Date updatedTime;
	public Integer getRevision() {
		return revision;
	}
	public void setRevision(Integer revision) {
		this.revision = revision;
	}
	public String getCreatedBy() {
		return createdBy;
	}
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}
	public Date getCreatedTime() {
		return createdTime;
	}
	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}
	public String getUpdatedBy() {
		return updatedBy;
	}
	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}
	public Date getUpdatedTime() {
		return updatedTime;
	}
	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}
	
}
