package auth.mapper;

import auth.model.Menu;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface MenuMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_auth_menu
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(List<Integer> list) throws Exception;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_auth_menu
	 * @mbg.generated
	 */
	int insert(Menu record) throws Exception;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_auth_menu
	 * @mbg.generated
	 */
	Menu selectByPrimaryKey(Integer id) throws Exception;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_auth_menu
	 * @mbg.generated
	 */
	List<Menu> selectAll() throws Exception;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_auth_menu
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Menu record) throws Exception;
	
	Menu selectByName(String name) throws Exception;
	
	List<Menu> selectByPid(@Param("id") Integer id) throws Exception;
	
}