package auth.mapper;

import auth.form.ModuleForm;
import auth.model.Module;
import java.util.List;

public interface ModuleMapper {
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_auth_module
	 * @mbg.generated
	 */
	int deleteByPrimaryKey(Integer id) throws Exception;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_auth_module
	 * @mbg.generated
	 */
	int insert(Module record) throws Exception;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_auth_module
	 * @mbg.generated
	 */
	Module selectByPrimaryKey(Integer id) throws Exception;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_auth_module
	 * @mbg.generated
	 */
	List<Module> selectAll(ModuleForm form) throws Exception;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user_auth_module
	 * @mbg.generated
	 */
	int updateByPrimaryKey(Module record) throws Exception;
	
	Module selectByName(String name) throws Exception;

}